changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - octocat
      - dependabot
  categories:
    - title: Exciting New Features 🎉
      labels:
        - "feat"
    - title: Improvements 🚀
      labels:
        - "refactor"
        - "perf"
    - title: Bug Fixes 🐞
      labels:
        - "fix"
    - title: Breaking Changes 🛠
      labels:
        - "breaking-change"
    - title: Other Changes
      labels:
        - "*"